version: "3.4"
services:
  dev_tools:
    depends_on:
      - localaws
      - dynamodb-ui
      - dynamodb-local-mock-unsupported-api
    image: mwaaas/ansible_playbook:latest-latest
    volumes:
      - ./:/usr/src/app
      - ./:/ansible/playbooks/roles/ansible-terraform
      - $HOME/.aws:/root/.aws
    environment:
      - ANSIBLE_STDOUT_CALLBACK=debug

  dynamodb-ui:
    depends_on:
      - dynamodb
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - 8001:8001

  dynamodb-local-mock-unsupported-api:
    depends_on:
      - dynamodb
    image: mwaaas/dynamodb_local_mock_unsupported_api:latest
    environment:
      - DYNAMO_HOST=dynamodb
      - DYNAMO_PORT=8000
    ports:
      - 8002:4567

  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - 3307:8000
    environment:
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret_key
      - "AWS_DEFAULT_REGION=eu-west-1"

  # localaws endpoints configuration  documentation
  # https://github.com/localstack/localstack#overview
  localaws:
    image: localstack/localstack:0.10.4
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8088}:${PORT_WEB_UI-8080}"
    environment:
      - "SERVICES=sts"
      - DEFAULT_REGION=eu-west-1
      - "HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL-localaws}"